### ISSUE TITLE
All sub-folders in thirdparty are empty

### ISSUE THREAD

**Issue by zhang-xun** [SteveWick/CGRA-ME#1]
Hi, in cgra-me-2.0 's thirdparty, all the submodule are empty, and there are no .git file for “git submodule update --recursive".
 

 The source directory

    /Users/zhangxun/cgra-me-release-v2.0.0/thirdparty/tatum

  does not contain a CMakeLists.txt file.

**Comment by zhang-xun** [comment]
i think it's just in tatum.

**Comment by zhang-xun** [comment]
target_link_libraries(cgra-me
    PUBLIC coreir
    PRIVATE pugixml
    PRIVATE libtatum
)

**Comment by SteveWick** [comment]
The build process has been updated in the latest version. Please re-download CGRA-ME from the [website](https://cgra-me.ece.utoronto.ca/download/) and try again.
